runtime: nodejs12
vpc_access_connector:
        name: projects/portfolio-285801/locations/us-east1/connectors/portfolio-vpc
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  
env_variables:
  SQL_USER: "postgres"
  SQL_PASSWORD: "Nhannon03231996!?><"
  SQL_DATABASE: "PortfolioDB"
  INSTANCE_CONNECTION_NAME: "portfolio-285801:us-east1:portfolio-db"

# beta_settings:
#   cloud_sql_instances: "portfolio-285801:us-east1:portfolio-db"
#   # cloud_sql_instances: portfolio-285502:us-east1:portfolio-db=tcp:5433