runtime: nodejs12
vpc_access_connector:
        name: projects/portfolio-285502/locations/us-east1/connectors/portfolio-vpc
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  
