// all image files are supported
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.svg'
declare module '*.webp'
declare module '*.ico'
declare module '*.bmp'
declare module '*.tiff'
